services:
  database:
    container_name: database
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}
    restart: always
    env_file:
      - path: .env
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/schema:/schema
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-postgres.sh

  etl-fin-api:
    container_name: etl-fin-api
    image: dataengineer24/etl-fin-api
    build: .
    env_file:
      - path: .env

volumes:
  database:
    driver: local

networks:
  default:
    name: dev-net
