import pytest
from datetime import date

from transform.schema_alpha_vantage import Company, IncomeStatementReport, BalanceSheetReport, CashFlowReport

def test_schema_company():
    # arrange
    ibm = {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines",
        "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TECHNOLOGY",
        "Industry": "COMPUTER & OFFICE EQUIPMENT",
        "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
        "OfficialSite": "https://www.ibm.com",
        "FiscalYearEnd": "December"
    }
    expect = {
         "symbol": "IBM",
         "asset_type": "Common Stock",
         "name": "International Business Machines",
         "description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
         "cik": "51143",
         "exchange": "NYSE",
         "currency": "USD",
         "country": "USA",
         "sector": "TECHNOLOGY",
         "industry": "COMPUTER & OFFICE EQUIPMENT",
         "address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
         "official_site": "https://www.ibm.com",
         "fiscal_year_end": "December"
    }
    # act
    test = Company.model_validate(ibm)
    # assert
    assert expect == test.model_dump()

def test_schema_income_statement_report():
    # arrange
    ibm = {
        "fiscalDateEnding": "2024-12-31",
        "reportedCurrency": "USD",
        "totalRevenue": "62753000000",
        "costofGoodsAndServicesSold": "27201000000",
        "grossProfit": "35551000000",
        "operatingIncome": "10074000000",
        "operatingExpenses": "25478000000",
        "interestAndDebtExpense": "None",
        "netIncome": "6023000000"
    }
    expect = {
        "symbol": None,
        "fiscal_date_ending": date(2024, 12, 31),
        "currency": "USD",
        "revenue": 62753000000,
        "cost_of_goods_sold": 27201000000,
        "gross_profit": 35551000000,
        "operating_income": 10074000000,
        "operating_expenses": 25478000000,
        "interest_and_debt_expense": None,
        "net_income": 6023000000
    }
    # act
    test = IncomeStatementReport.model_validate(ibm)
    # assert
    assert expect == test.model_dump()

def test_schema_balance_sheet_report():
    # arrange
    ibm = {
        "fiscalDateEnding": "2024-12-31",
        "reportedCurrency": "USD",
        "totalAssets": "137175000000",
        "totalCurrentAssets": "34482000000",
        "totalNonCurrentAssets": "102694000000",
        "totalLiabilities": "109782000000",
        "totalCurrentLiabilities": "33142000000",
        "totalNonCurrentLiabilities": "76640000000",
        "totalShareholderEquity": "27307000000",
        "inventory": "1289000000",
        "currentAccountsPayable": "4032000000",
        "cashAndCashEquivalentsAtCarryingValue": "13947000000",
        "currentNetReceivables": "14010000000",
        "commonStockSharesOutstanding": "937200000"
    }
    expect = {
        "symbol": None,
        "fiscal_date_ending": date(2024, 12, 31),
        "currency": "USD",
        "total_assets": 137175000000,
        "total_current_assets": 34482000000,
        "total_non_current_assets": 102694000000,
        "total_liabilities": 109782000000,
        "total_current_liabilities": 33142000000,
        "total_non_current_liabilities": 76640000000,
        "total_shareholder_equity": 27307000000,
        "inventory": 1289000000,
        "current_accounts_payable": 4032000000,
        "cash_and_cash_equivalents": 13947000000,
        "current_net_receivables": 14010000000,
        "shares_outstanding": 937200000
    }
    # act
    test = BalanceSheetReport.model_validate(ibm)
    # assert
    assert expect == test.model_dump()

def test_schema_cash_flow_report():
    # arrange
    ibm = {
        "fiscalDateEnding": "2024-12-31",
        "reportedCurrency": "USD",
        "operatingCashflow": "13445000000",
        "cashflowFromInvestment": "None",
        "cashflowFromFinancing": "-7079000000",
        "dividendPayout": "6147000000"
    }
    expect = {
        "symbol": None,
        "fiscal_date_ending": date(2024, 12, 31),
        "currency": "USD",
        "cash_flow_operations": 13445000000,
        "cash_flow_investments": 0,
        "cash_flow_financing": -7079000000,
        "dividend_payout": 6147000000
    }
    # act
    test = CashFlowReport.model_validate(ibm)
    # assert
    assert expect == test.model_dump()
